build: use casual-version

diff --git a/.github/workflows/casual-build-alpha.yaml b/.github/workflows/casual-build-alpha.yaml
--- a/.github/workflows/casual-build-alpha.yaml
+++ b/.github/workflows/casual-build-alpha.yaml
@@ -7,18 +7,25 @@ on:
       - 'patch/**'
       - '!patch/*/main'
 env:
-  build_type: alpha
+  release-type: alpha
   ubi_image: casual/ubi8-builder
 
 jobs:
   calculate-version:
     runs-on: ubuntu-latest
+    outputs:
+      major-minor: ${{ steps.version.outputs.major-minor }}
+      build-version: ${{ steps.version.outputs.build-version }}
+      casual-version: ${{ steps.version.outputs.casual-version }}
+      casual-release: ${{ steps.version.outputs.casual-release }}
     steps:
       - uses: actions/checkout@v6
-      - uses: casualcore/casual-version@6a8d033b9b6dae5efcf56b69ff13f4d9bb3918cc
+        with:
+          fetch-depth: 0
+      - uses: casualcore/casual-version@0.1
         id: version
         with:
-          build_type: env.alpha
+          release-type: ${{ env.release-type }}
   
   notification-start:
     runs-on: ubuntu-latest
@@ -29,7 +36,7 @@ jobs:
           DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
         uses: Ilshidur/action-discord@0.3.2
         with:
-          args: "Starting a new build, Repo: ${{ github.repository }}, Branch: ${{ github.ref_name }}, Version: ${{ needs.calculate-version.outputs.build_version }}, URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"           
+          args: "Starting a new build, Repo: ${{ github.repository }}, Branch: ${{ github.ref_name }}, Version: ${{ needs.calculate-version.outputs.build-version }}, URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"           
   
   build-ubi:
     runs-on: [self-hosted, builder]
@@ -39,7 +46,7 @@ jobs:
       DISTRIBUTION: 'ubi'
     steps:
       - name: check out repository casual
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           path: 'casual'
           fetch-depth: 0
@@ -63,12 +70,12 @@ jobs:
           chmod 777 /git/casual/casual.log
 
           mkdir -p \${CMAKE_BINARY_DIR}
-          echo "set(CPACK_RPM_PACKAGE_VERSION ${{ needs.calculate-version.outputs.casual_version }})" > \${CMAKE_BINARY_DIR}/version.cmake
-          echo "set(CPACK_RPM_PACKAGE_RELEASE ${{ needs.calculate-version.outputs.casual_release }})" >> \${CMAKE_BINARY_DIR}/version.cmake
+          echo "set(CPACK_RPM_PACKAGE_VERSION ${{ needs.calculate-version.outputs.casual-version }})" > \${CMAKE_BINARY_DIR}/version.cmake
+          echo "set(CPACK_RPM_PACKAGE_RELEASE ${{ needs.calculate-version.outputs.casual-release }})" >> \${CMAKE_BINARY_DIR}/version.cmake
 
           cat \${CMAKE_BINARY_DIR}/version.cmake
 
-          bash /git/casual/casual/pipeline/script/backend/$DISTRIBUTION/build ${{ needs.calculate-version.outputs.build_version }}
+          bash /git/casual/casual/pipeline/script/backend/$DISTRIBUTION/build ${{ needs.calculate-version.outputs.build-version }}
           CODE=$?
 
           find \${CMAKE_BINARY_DIR} -name 'casual-middleware-*.rpm' -exec cp "{}" /git/casual/casual/results  \;
@@ -83,29 +90,29 @@ jobs:
 
           chmod +x builder.sh
 
-      # - name: Build
-      #   run: |
-      #     docker run --rm -v ${{ github.workspace }}:/git/casual:Z -i ${{ env.ubi_image}}:${{ needs.calculate-version.outputs.major_minor }}-cmake
+      - name: Build
+        run: |
+          docker run --rm -v ${{ github.workspace }}:/git/casual:Z -i ${{ env.ubi_image}}:${{ needs.calculate-version.outputs.major-minor }}-cmake
 
-      # - name: Logpublisher
-      #   if: ${{ failure() || cancelled() }}
-      #   run: |
-      #     ${{ github.workspace }}/casual/pipeline/script/post/logpublisher ${{ github.workspace }}/casual.log ${DISTRIBUTION}-${{ needs.calculate-version.outputs.build_version }}
+      - name: Logpublisher
+        if: ${{ failure() || cancelled() }}
+        run: |
+          ${{ github.workspace }}/casual/pipeline/script/post/logpublisher ${{ github.workspace }}/casual.log ${DISTRIBUTION}-${{ needs.calculate-version.outputs.build-version }}
 
-      # - name: Test Report
-      #   uses: dorny/test-reporter@v2
-      #   if: ${{ success() || failure() }}    # run this step even if previous step failed
-      #   with:
-      #     name: Google Tests - Ubi # Name of the check run which will be created
-      #     path: ./**/report.xml       # Path to test results
-      #     reporter: java-junit        # Format of test result
-      #     working-directory: casual
+      - name: Test Report
+        uses: dorny/test-reporter@v2
+        if: ${{ success() || failure() }}    # run this step even if previous step failed
+        with:
+          name: Google Tests - Ubi # Name of the check run which will be created
+          path: ./**/report.xml       # Path to test results
+          reporter: java-junit        # Format of test result
+          working-directory: casual
 
-      # - name: Save artifact
-      #   uses: actions/upload-artifact@v4
-      #   with:
-      #     name: ubi_rpm
-      #     path: ./**/casual-middleware*.rpm
+      - name: Save artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: ubi_rpm
+          path: ./**/casual-middleware*.rpm
 
 
   notification-end:
@@ -120,4 +127,4 @@ jobs:
           DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
         uses: Ilshidur/action-discord@0.3.2
         with:
-          args: "Build status ${{ steps.check.outputs.status }}, Repo: ${{ github.repository }}, Branch: ${{ github.ref_name }}, Version: ${{ needs.calculate-version.outputs.build_version }}, URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"           
+          args: "Build status ${{ steps.check.outputs.status }}, Repo: ${{ github.repository }}, Branch: ${{ github.ref_name }}, Version: ${{ needs.calculate-version.outputs.build-version }}, URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"           
